CREATE OR REPLACE TABLE FACT_PEDIDOS AS
SELECT
    D.CCODPEDIDO AS ID_PEDIDO,
    D.CCODCAMPANA AS ID_CAMPANA,
    D.CCODCLIENTE AS ID_VENDEDOR,
    F.ID AS ID_FECHA,
    V.ID_COORDINADORA,
    U.ID_UBICACION,
    D.NMONPEDIDO AS MONTO_TOTAL_PEDIDO,
    D.NMONPAGO AS MONTO_PAGADO,
    IFF(
        TO_CHAR(V.FECHA_INGRESO, 'YYYY-MM') = TO_CHAR(D.DFECPEDIDO, 'YYYY-MM'),
        1, 0
    ) AS ES_NUEVA_VENDEDORA,
    D.TIPO
FROM STG_DOCUMENTO D
LEFT JOIN DIM_FECHA F ON D.DFECPEDIDO = F.DATE
LEFT JOIN DIM_VENDEDOR V ON D.CCODCLIENTE = V.ID_VENDEDOR
LEFT JOIN DIM_UBICACION U ON V.CCODUBIGEO = U.CCODUBIGEO;
