CREATE OR REPLACE TABLE FACT_PEDIDOS_DETALLE AS
SELECT
    D.CCODPEDIDO AS ID_PEDIDO,
    P.ID_CAMPANA AS ID_CAMPANA,
    P.ID_VENDEDOR AS ID_VENDEDOR,
    P.ID_FECHA AS ID_FECHA,
    P.ID_UBICACION AS ID_UBICACION,
    D.IDPEDIDO AS ID_PEDIDO_DETALLE,
    D.CCODCONTENIDO AS ID_PRODUCTO,
    TRY_CAST(D.NCANTIDAD AS FLOAT) AS CANTIDAD,
    TRY_CAST(D.NIMPORTE AS FLOAT) AS IMPORTE_PRODUCTO
FROM STG_DOCUMENTODETALLE D
LEFT JOIN FACT_PEDIDOS P ON D.CCODPEDIDO = P.ID_PEDIDO
LEFT JOIN DIM_PRODUCTO PR ON D.CCODCONTENIDO = PR.ID_PRODUCTO;

DROP TABLE IF EXISTS STG_DOCUMENTO;
DROP TABLE IF EXISTS STG_DOCUMENTODETALLE;

SELECT 
    *,
    ROW_NUMBER() OVER (ORDER BY TO_DATE(FECHA_INICIO) ASC) AS NUMERO_CAMPANA
FROM DIM_CAMPANA
